DROP DATABASE IF EXISTS QQBOT;

CREATE DATABASE QQBOT;
USE QQBOT;

CREATE TABLE JSESSIONID
(
    UID        BIGINT      NOT NULL COMMENT 'USER QQ',
    JSESSIONID VARCHAR(32) NOT NULL COMMENT 'Codeforces JSESSIONID',
    PRIMARY KEY (UID)
)
COMMENT 'Codeforces JSESSIONID';