DROP DATABASE IF EXISTS QQBOT;

CREATE DATABASE QQBOT;
USE QQBOT;

CREATE TABLE JSESSIONID
(
    GID        BIGINT      NOT NULL COMMENT 'GROUP QQ',
    UID        BIGINT      NOT NULL COMMENT 'USER QQ',
    JSESSIONID VARCHAR(32) NOT NULL COMMENT 'Codeforces JSESSIONID',
    PRIMARY KEY (GID, UID)
)
COMMENT 'Codeforces JSESSIONID' CHARSET 'BINARY';